INSERT INTO ofVersion (name, version) VALUES ('kanban', 2);

CREATE TABLE ofKanbanBoard (boardID VARCHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, revision BIGINT NOT NULL, activitySequence BIGINT DEFAULT 0 NOT NULL, createdBy VARCHAR(1024) NOT NULL, createdAt BIGINT NOT NULL, updatedAt BIGINT NOT NULL, discussionRoomJID VARCHAR(1024) NULL);
CREATE TABLE ofKanbanColumn (columnID VARCHAR(36) PRIMARY KEY, boardID VARCHAR(36) NOT NULL REFERENCES ofKanbanBoard(boardID), name VARCHAR(255) NOT NULL, rank VARCHAR(255) NOT NULL, wipLimit INTEGER NOT NULL, createdAt BIGINT NOT NULL, UNIQUE(boardID, rank));
CREATE TABLE ofKanbanCard (cardID VARCHAR(36) PRIMARY KEY, boardID VARCHAR(36) NOT NULL REFERENCES ofKanbanBoard(boardID), columnID VARCHAR(36) NOT NULL REFERENCES ofKanbanColumn(columnID), revision BIGINT NOT NULL, rank VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NULL, assigneeJID VARCHAR(1024) NULL, priority VARCHAR(16) DEFAULT 'NONE' NOT NULL, discussionThreadID VARCHAR(255) NULL, deleted INTEGER NOT NULL, createdBy VARCHAR(1024) NOT NULL, createdAt BIGINT NOT NULL, updatedAt BIGINT NOT NULL, deletedAt BIGINT NULL, UNIQUE(columnID, rank));
CREATE TABLE ofKanbanLabel (labelID VARCHAR(36) PRIMARY KEY, boardID VARCHAR(36) NOT NULL REFERENCES ofKanbanBoard(boardID), name VARCHAR(32) NOT NULL, color VARCHAR(16) NOT NULL, createdAt BIGINT NOT NULL);
CREATE TABLE ofKanbanCardLabel (cardID VARCHAR(36) NOT NULL REFERENCES ofKanbanCard(cardID), labelID VARCHAR(36) NOT NULL REFERENCES ofKanbanLabel(labelID), position INTEGER NOT NULL, PRIMARY KEY(cardID, labelID), UNIQUE(cardID, position));
CREATE TABLE ofKanbanMember (memberID VARCHAR(36) PRIMARY KEY, boardID VARCHAR(36) NOT NULL REFERENCES ofKanbanBoard(boardID), bareJID VARCHAR(1024) NOT NULL, role VARCHAR(16) NOT NULL, createdAt BIGINT NOT NULL, UNIQUE(boardID, bareJID));
CREATE TABLE ofKanbanActivity (activityID VARCHAR(36) PRIMARY KEY, boardID VARCHAR(36) NOT NULL REFERENCES ofKanbanBoard(boardID), sequence BIGINT NOT NULL, eventType VARCHAR(32) NOT NULL, actorJID VARCHAR(1024) NOT NULL, entityID VARCHAR(36) NOT NULL, payload TEXT NOT NULL, occurredAt BIGINT NOT NULL, UNIQUE(boardID, sequence));
CREATE TABLE ofKanbanOutbox (outboxID VARCHAR(36) PRIMARY KEY, boardID VARCHAR(36) NOT NULL REFERENCES ofKanbanBoard(boardID), sequence BIGINT NOT NULL, kind VARCHAR(32) NOT NULL, nodeID VARCHAR(255) NOT NULL, itemID VARCHAR(36) NOT NULL, payload TEXT NOT NULL, status VARCHAR(16) NOT NULL, attempts INTEGER NOT NULL, availableAt BIGINT NOT NULL, leaseOwner VARCHAR(255) NULL, leaseUntil BIGINT NULL, lastError VARCHAR(2000) NULL, createdAt BIGINT NOT NULL, deliveredAt BIGINT NULL, UNIQUE(boardID, sequence));
CREATE INDEX ofKanbanCard_board_idx ON ofKanbanCard (boardID, deleted);
CREATE INDEX ofKanbanLabel_board_idx ON ofKanbanLabel (boardID);
CREATE INDEX ofKanbanCardLabel_label_idx ON ofKanbanCardLabel (labelID);
CREATE INDEX ofKanbanOutbox_ready_idx ON ofKanbanOutbox (status, availableAt);
